package me.meowcher.winnerpov.control.utils

import net.minecraft.network.packet.c2s.handshake.HandshakeC2SPacket
import net.minecraft.network.packet.c2s.login.LoginHelloC2SPacket
import net.minecraft.network.packet.c2s.login.LoginKeyC2SPacket
import net.minecraft.network.packet.c2s.login.LoginQueryResponseC2SPacket
import net.minecraft.network.packet.c2s.play.*
import net.minecraft.network.packet.c2s.query.QueryPingC2SPacket
import net.minecraft.network.packet.c2s.query.QueryRequestC2SPacket
import net.minecraft.network.packet.s2c.login.*
import net.minecraft.network.packet.s2c.play.*
import net.minecraft.network.packet.s2c.query.QueryPongS2CPacket
import net.minecraft.network.packet.s2c.query.QueryResponseS2CPacket
import java.util.ArrayList

object ClassUtils {

    val arrayListPackets : ArrayList<Class<*>> = arrayListOf(
        AdvancementTabC2SPacket::class.java,
        AdvancementUpdateS2CPacket::class.java,
        BlockBreakingProgressS2CPacket::class.java,
        BlockEntityUpdateS2CPacket::class.java,
        BlockEventS2CPacket::class.java,
        BlockUpdateS2CPacket::class.java,
        BoatPaddleStateC2SPacket::class.java,
        BookUpdateC2SPacket::class.java,
        BossBarS2CPacket::class.java,
        ButtonClickC2SPacket::class.java,
        ChatMessageC2SPacket::class.java,
        ChunkDataS2CPacket::class.java,
        ChunkDeltaUpdateS2CPacket::class.java,
        ChunkLoadDistanceS2CPacket::class.java,
        ChunkRenderDistanceCenterS2CPacket::class.java,
        ClearTitleS2CPacket::class.java,
        ClickSlotC2SPacket::class.java,
        ClientCommandC2SPacket::class.java,
        ClientSettingsC2SPacket::class.java,
        ClientStatusC2SPacket::class.java,
        CloseHandledScreenC2SPacket::class.java,
        CloseScreenS2CPacket::class.java,
        CommandSuggestionsS2CPacket::class.java,
        CommandTreeS2CPacket::class.java,
        CooldownUpdateS2CPacket::class.java,
        CraftFailedResponseS2CPacket::class.java,
        CraftRequestC2SPacket::class.java,
        CreativeInventoryActionC2SPacket::class.java,
        CustomPayloadC2SPacket::class.java,
        CustomPayloadS2CPacket::class.java,
        DeathMessageS2CPacket::class.java,
        DifficultyS2CPacket::class.java,
        DisconnectS2CPacket::class.java,
        EndCombatS2CPacket::class.java,
        EnterCombatS2CPacket::class.java,
        EntitiesDestroyS2CPacket::class.java,
        EntityAnimationS2CPacket::class.java,
        EntityAttachS2CPacket::class.java,
        EntityAttributesS2CPacket::class.java,
        EntityEquipmentUpdateS2CPacket::class.java,
        EntityPassengersSetS2CPacket::class.java,
        EntityPositionS2CPacket::class.java,
        EntityS2CPacket::class.java,
        EntityS2CPacket.MoveRelative::class.java,
        EntityS2CPacket.Rotate::class.java,
        EntityS2CPacket.RotateAndMoveRelative::class.java,
        EntitySetHeadYawS2CPacket::class.java,
        EntitySpawnS2CPacket::class.java,
        EntityStatusEffectS2CPacket::class.java,
        EntityStatusS2CPacket::class.java,
        EntityTrackerUpdateS2CPacket::class.java,
        EntityVelocityUpdateS2CPacket::class.java,
        ExperienceBarUpdateS2CPacket::class.java,
        ExperienceOrbSpawnS2CPacket::class.java,
        ExplosionS2CPacket::class.java,
        GameJoinS2CPacket::class.java,
        GameMessageS2CPacket::class.java,
        GameStateChangeS2CPacket::class.java,
        HandshakeC2SPacket::class.java,
        HandSwingC2SPacket::class.java,
        HealthUpdateS2CPacket::class.java,
        InventoryS2CPacket::class.java,
        ItemPickupAnimationS2CPacket::class.java,
        JigsawGeneratingC2SPacket::class.java,
        KeepAliveC2SPacket::class.java,
        KeepAliveS2CPacket::class.java,
        LightUpdateS2CPacket::class.java,
        LoginCompressionS2CPacket::class.java,
        LoginDisconnectS2CPacket::class.java,
        LoginHelloC2SPacket::class.java,
        LoginHelloS2CPacket::class.java,
        LoginKeyC2SPacket::class.java,
        LoginQueryRequestS2CPacket::class.java,
        LoginQueryResponseC2SPacket::class.java,
        LoginSuccessS2CPacket::class.java,
        LookAtS2CPacket::class.java,
        MapUpdateS2CPacket::class.java,
        NbtQueryResponseS2CPacket::class.java,
        OpenHorseScreenS2CPacket::class.java,
        OpenScreenS2CPacket::class.java,
        OpenWrittenBookS2CPacket::class.java,
        OverlayMessageS2CPacket::class.java,
        ParticleS2CPacket::class.java,
        PickFromInventoryC2SPacket::class.java,
        PlayerAbilitiesS2CPacket::class.java,
        PlayerActionC2SPacket::class.java,
        PlayerActionResponseS2CPacket::class.java,
        PlayerInputC2SPacket::class.java,
        PlayerInteractBlockC2SPacket::class.java,
        PlayerInteractEntityC2SPacket::class.java,
        PlayerInteractItemC2SPacket::class.java,
        PlayerListHeaderS2CPacket::class.java,
        PlayerListS2CPacket::class.java,
        PlayerMoveC2SPacket::class.java,
        PlayerMoveC2SPacket.Full::class.java,
        PlayerMoveC2SPacket.LookAndOnGround::class.java,
        PlayerMoveC2SPacket.OnGroundOnly::class.java,
        PlayerMoveC2SPacket.PositionAndOnGround::class.java,
        PlayerPositionLookS2CPacket::class.java,
        PlayerRespawnS2CPacket::class.java,
        PlayerSpawnPositionS2CPacket::class.java,
        PlayerSpawnS2CPacket::class.java,
        PlaySoundFromEntityS2CPacket::class.java,
        PlaySoundIdS2CPacket::class.java,
        PlaySoundS2CPacket::class.java,
        QueryBlockNbtC2SPacket::class.java,
        QueryEntityNbtC2SPacket::class.java,
        QueryPingC2SPacket::class.java,
        QueryPongS2CPacket::class.java,
        QueryRequestC2SPacket::class.java,
        QueryResponseS2CPacket::class.java,
        RecipeBookDataC2SPacket::class.java,
        RecipeCategoryOptionsC2SPacket::class.java,
        RemoveEntityStatusEffectS2CPacket::class.java,
        RenameItemC2SPacket::class.java,
        RequestCommandCompletionsC2SPacket::class.java,
        ResourcePackSendS2CPacket::class.java,
        ResourcePackStatusC2SPacket::class.java,
        ScoreboardDisplayS2CPacket::class.java,
        ScoreboardObjectiveUpdateS2CPacket::class.java,
        ScoreboardPlayerUpdateS2CPacket::class.java,
        ScreenHandlerPropertyUpdateS2CPacket::class.java,
        ScreenHandlerSlotUpdateS2CPacket::class.java,
        SelectAdvancementTabS2CPacket::class.java,
        SelectMerchantTradeC2SPacket::class.java,
        SetCameraEntityS2CPacket::class.java,
        SetTradeOffersS2CPacket::class.java,
        SignEditorOpenS2CPacket::class.java,
        SpectatorTeleportC2SPacket::class.java,
        StatisticsS2CPacket::class.java,
        StopSoundS2CPacket::class.java,
        SubtitleS2CPacket::class.java,
        SynchronizeRecipesS2CPacket::class.java,
        SynchronizeTagsS2CPacket::class.java,
        TeamS2CPacket::class.java,
        TeleportConfirmC2SPacket::class.java,
        TitleFadeS2CPacket::class.java,
        TitleS2CPacket::class.java,
        UnloadChunkS2CPacket::class.java,
        UnlockRecipesS2CPacket::class.java,
        UpdateBeaconC2SPacket::class.java,
        UpdateCommandBlockC2SPacket::class.java,
        UpdateCommandBlockMinecartC2SPacket::class.java,
        UpdateDifficultyC2SPacket::class.java,
        UpdateDifficultyLockC2SPacket::class.java,
        UpdateJigsawC2SPacket::class.java,
        UpdatePlayerAbilitiesC2SPacket::class.java,
        UpdateSelectedSlotC2SPacket::class.java,
        UpdateSelectedSlotS2CPacket::class.java,
        UpdateSignC2SPacket::class.java,
        UpdateStructureBlockC2SPacket::class.java,
        VehicleMoveC2SPacket::class.java,
        VehicleMoveS2CPacket::class.java,
        WorldBorderCenterChangedS2CPacket::class.java,
        WorldBorderInitializeS2CPacket::class.java,
        WorldBorderInterpolateSizeS2CPacket::class.java,
        WorldBorderSizeChangedS2CPacket::class.java,
        WorldBorderWarningBlocksChangedS2CPacket::class.java,
        WorldBorderWarningTimeChangedS2CPacket::class.java,
        WorldEventS2CPacket::class.java,
        WorldTimeUpdateS2CPacket::class.java
    )
}